apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
  labels:
    name: store-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "*.store.local.com"
      http:
        paths:
          - path: /auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: store-auth
                port:
                  number: 5000
          - path: /user/?(.*)
            pathType: Prefix
            backend:
              service:
                name: store-users
                port:
                  number: 5200
          - path: /product/?(.*)
            pathType: Prefix
            backend:
              service:
                name: store-products
                port:
                  number: 5200