version: '3.8'

name: store

services:

  pgadmin:
    container_name: store-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@store.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 8080:80
    networks:
      - store-network

networks:
  store-network:
    driver: bridge