apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
  labels:
    name: store-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://$host/auth/validate"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.host.api }}	
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-service" .Values.store.service.auth.name }}
                port:
                  number: {{ .Values.store.service.auth.port }}
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-service" .Values.store.service.users.name }}
                port:
                  number: {{ .Values.store.service.users.port }}
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-service" .Values.store.service.products.name }}
                port:
                  number: {{ .Values.store.service.products.port }}