apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-auth
  template:
    metadata:
      labels:
        app: store-auth
    spec:
      containers:
        - name: store-auth
          image: alexandergv2117/store-auth
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "admin"
            - name: DB_NAME
              value: "store_users"
            - name: JWT_SECRET
              value: "secret"
            - name: PUBLIC_KEY
              value: ""