apiVersion: v1
kind: Service
metadata:
  name: store-auth
  labels:
    app: store-auth
spec:
  selector:
    app: store-auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort