apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-products
  template:
    metadata:
      labels:
        app: store-products
    spec:
      containers:
        - name: store-products
          image: alexandergv2117/store-products
          ports:
            - containerPort: 5300
          env:
            - name: DB_HOST
              value: "postgres-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "admin"
            - name: DB_NAME
              value: "store_products"
            - name: DB_LOGGING
              value: "false"