apiVersion: v1
kind: Service
metadata:
  name: store-products
  labels:
    app: store-products
spec:
  selector:
    app: store-products
  ports:
    - protocol: TCP
      port: 5300
      targetPort: 5300
  type: NodePort