global:
  postgresql:
    name: "postgresql-service"
    type: NodePort
    port: 5432
    protocol: TCP
    username: "admin"
    password: "admin"
    database: "postgres"
    replicas: 1
    image: "postgres:16.2"
    extraDatabase: "store_users,store_products"

  host:
    api: "api.store.com"

store:
  service:
    auth:
      name: "store-auth"
      port: 5000
      type: NodePort
      strategy: RollingUpdate
      replicas: 1
      image: "alexandergv2117/store-auth"
      env:
        DB_HOST: "postgresql-service"
        DB_PORT: 5432
        DB_USERNAME: "admin"
        DB_PASSWORD: "admin"
        DB_NAME: "store_users"
        JWT_SECRET: "secret"
        PUBLIC_KEY: ""

    users:
      name: "store-users"
      port: 5200
      type: NodePort
      strategy: RollingUpdate
      replicas: 1
      image: "alexandergv2117/store-users"
      env:
        DB_HOST: "postgresql-service"
        DB_PORT: 5432
        DB_USERNAME: "admin"
        DB_PASSWORD: "admin"
        DB_NAME: "store_users"
      
    products:
      name: "store-products"
      port: 5300
      type: NodePort
      strategy: RollingUpdate
      replicas: 1
      image: "alexandergv2117/store-products"
      env:
        DB_HOST: "postgresql-service"
        DB_PORT: 5432
        DB_USERNAME: "admin"
        DB_PASSWORD: "admin"
        DB_NAME: "store_products"