global:
  namespace: "store"
  postgresql:
    name: "postgresql-service"
    type: NodePort
    port: 5432
    protocol: TCP
    username: "admin"
    password: "admin"
    database: "postgres"
    replicas: 1
    image: "postgres:16.2"
    extraDatabase: "store_users,store_products"

  host:
    api: "api.store.com"

  ingress:
    name: "store-ingress"
    ingressClassName: "nginx"
  
store:
  service:
    auth:
      name: "store-auth"
      port: 5000
      type: NodePort
      strategy: RollingUpdate
      replicas: 3
      minReplicas: 1
      maxReplicas: 10
      cpuUtilization: 80
      image: "alexandergv2117/store-auth-svc-fiber-backend"
      env:
        - name: DB_HOST
          value: "postgresql-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: DB_NAME
          value: "store_users"
        - name: JWT_SECRET
          value: "secret"

    users:
      name: "store-users"
      port: 5200
      type: NodePort
      strategy: RollingUpdate
      replicas: 3
      minReplicas: 1
      maxReplicas: 10
      cpuUtilization: 80
      image: "alexandergv2117/store-users-svc-nestjs-backend"
      env:
        - name: DB_HOST
          value: "postgresql-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: DB_NAME
          value: "store_users"
        - name: AWS_BUCKET_NAME_IMAGE
          value: ""
        - name: AWS_BUCKET_NAME_REGION
          value: ""
        - name: AWS_PUBLIC_KEY
          value: ""
        - name: AWS_SECRET_KEY
          value: ""
      
    products:
      name: "store-products"
      port: 5300
      type: NodePort
      strategy: RollingUpdate
      replicas: 3
      minReplicas: 1
      maxReplicas: 10
      cpuUtilization: 80
      image: "alexandergv2117/store-products-svc-nestjs-backend"
      env:
        - name: "DB_HOST"
          value: "postgresql-service"
        - name: "DB_PORT"
          value: "5432"
        - name: "DB_USERNAME"
          value: "admin"
        - name: "DB_PASSWORD"
          value: "admin"
        - name: "DB_NAME"
          value: "store_products"
        - name: AWS_BUCKET_NAME_IMAGE
          value: ""
        - name: AWS_BUCKET_NAME_REGION
          value: ""
        - name: AWS_PUBLIC_KEY
          value: ""
        - name: AWS_SECRET_KEY
          value: ""