apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ printf "%s-deployment" .Values.store.service.users.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.store.service.users.name }}
  minReplicas: {{ .Values.store.service.users.minReplicas }}
  maxReplicas: {{ .Values.store.service.users.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.store.service.users.cpuUtilization }}
