apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ printf "%s-service" .Values.store.service.users.name }}
  labels:
    app: {{ .Values.store.service.users.name }}
spec:
  selector:
    app: {{ .Values.store.service.users.name }}
    role: {{ .Values.store.service.users.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.store.service.users.port }}
      targetPort: {{ .Values.store.service.users.port }}
  type: {{ .Values.store.service.users.type }}