apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.postgresql.name }}
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: {{ .Values.global.postgresql.protocol }}
      port: {{ .Values.global.postgresql.port }}
      targetPort: {{ .Values.global.postgresql.port }}
  type: {{ .Values.global.postgresql.type }}
