name: Publish Image to Docker Hub

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - 
        name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Switch to branch
        run: git checkout ${{ github.event.pull_request.head.ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Find prefix and service name
        id: find_prefix_and_service
        run: ./scripts/find_prefix_and_service.sh

      - name: Echo prefix and service name
        run: echo ${{ steps.find_prefix_and_service.outputs.prefixe }} ${{ steps.find_prefix_and_service.outputs.service }}
      
      - name: Build and push image to Docker Hub
        if : ${{ steps.find_prefix_and_service.outputs.prefixe == 'feat' && steps.find_prefix_and_service.outputs.service != ''}}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./services/${{ steps.find_prefix_and_service.outputs.service }}/.
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/store-${{ steps.find_prefix_and_service.outputs.service }}:latest
