name: Publish Image Auth svc to Docker Hub

on:
  push:
    branches:
      - feat/deploy

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - 
        name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  docker:
    if: startsWith(github.event.head_commit.message, 'publish(users):')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./services/users/.
          file: ./services/users/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/store-users-svc-nestjs-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/store-users-svc-nestjs-backend:latest
